celebrity_instagram_data = {
    'Cristiano Ronaldo': {'followers': 538, 'profession': 'Footballer', 'country': 'Portugal'},
    'Ariana Grande': {'followers': 329, 'profession': 'Singer', 'country': 'USA'}, 
    'Dwayne Johnson': {'followers': 328, 'profession': 'Actor', 'country': 'USA'},
    'Kylie Jenner': {'followers': 320, 'profession': 'Reality TV star', 'country': 'USA'},
    'Selena Gomez': {'followers': 340, 'profession': 'Singer/Actress', 'country': 'USA'},
    'Kim Kardashian': {'followers': 312, 'profession': 'Reality TV star', 'country': 'USA'},
    'Lionel Messi': {'followers': 367, 'profession': 'Footballer', 'country': 'Argentina'},
    'Beyoncé': {'followers': 270, 'profession': 'Singer', 'country': 'USA'},
    'Justin Bieber': {'followers': 237, 'profession': 'Singer', 'country': 'Canada'},
    'Kendall Jenner': {'followers': 257, 'profession': 'Model', 'country': 'USA'},
    'National Geographic': {'followers': 209, 'profession': 'Magazine', 'country': 'USA'},
    'Taylor Swift': {'followers': 214, 'profession': 'Singer', 'country': 'USA'},
    'Jennifer Lopez': {'followers': 215, 'profession': 'Singer/Actress', 'country': 'USA'}, 
    'Nicki Minaj': {'followers': 183, 'profession': 'Rapper', 'country': 'Trinidad'},
    'Nike': {'followers': 221, 'profession': 'Sports brand', 'country': 'USA'},
    'Khloe Kardashian': {'followers': 262, 'profession': 'Reality TV star', 'country': 'USA'},
    'Miley Cyrus': {'followers': 165, 'profession': 'Singer/Actress', 'country': 'USA'},
    'Katy Perry': {'followers': 150, 'profession': 'Singer', 'country': 'USA'},
    'Kourtney Kardashian': {'followers': 163, 'profession': 'Reality TV star', 'country': 'USA'},
    'Kevin Hart': {'followers': 144, 'profession': 'Comedian', 'country': 'USA'},
    'Real Madrid C.F.': {'followers': 115, 'profession': 'Football club', 'country': 'Spain'},
    'FC Barcelona': {'followers': 104, 'profession': 'Football club', 'country': 'Spain'},
    'NASA': {'followers': 73, 'profession': 'Space agency', 'country': 'USA'},
    'LeBron James': {'followers': 127, 'profession': 'Basketball player', 'country': 'USA'},
    'Vin Diesel': {'followers': 71, 'profession': 'Actor', 'country': 'USA'},
    'David Beckham': {'followers': 73, 'profession': 'Footballer', 'country': 'England'}, 
    'Billie Eilish': {'followers': 106, 'profession': 'Singer', 'country': 'USA'},
    'Chris Brown': {'followers': 64, 'profession': 'Singer', 'country': 'USA'},
    'Cardi B': {'followers': 138, 'profession': 'Rapper', 'country': 'USA'},
    'Drake': {'followers': 120, 'profession': 'Rapper', 'country': 'Canada'},
    'The Rock': {'followers': 345, 'profession': 'Actor/Wrestler', 'country': 'USA'},
    'Neymar Jr': {'followers': 167, 'profession': 'Footballer', 'country': 'Brazil'},
    'Justin Timberlake': {'followers': 59, 'profession': 'Singer/Actor', 'country': 'USA'},
    'Zendaya': {'followers': 152, 'profession': 'Actress/Singer', 'country': 'USA'},
    'Shakira': {'followers': 76, 'profession': 'Singer', 'country': 'Colombia'},
    'Bruno Mars': {'followers': 56, 'profession': 'Singer', 'country': 'USA'},
    'Chris Hemsworth': {'followers': 55, 'profession': 'Actor', 'country': 'Australia'},
    'UEFA Champions League': {'followers': 50, 'profession': 'Football competition', 'country': 'Europe'},
    'NBA': {'followers': 58, 'profession': 'Basketball league', 'country': 'USA'},
    'Virat Kohli': {'followers': 213, 'profession': 'Cricketer', 'country': 'India'}    
}